import type { Metadata } from "next";
import "./globals.css";
import DevDesignSystemLink from "@/components/DevDesignSystemLink";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        <DevDesignSystemLink />
      </body>
    </html>
  );
}
